fragment Salary on Salary {
  amount
  company {
    description
    domain
  }
  countryCode
  currencyCode
  amount
  gender
  genderOtherText
  id
  typeOfEmployment
  workMetodology
  workRole {
    description
    id
    name
    seniority
  }
  yearsOfExperience
}
