/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated. Please do not modify it manually. */
import * as Types from '../../../../api/gql/graphql';

import { gql } from '@apollo/client';
export type SalaryFragment = { __typename?: 'Salary', amount: number, countryCode: string, currencyCode: string, gender?: Types.Gender | null, genderOtherText?: string | null, id: string, typeOfEmployment: Types.TypeOfEmployment, workMetodology: Types.WorkMetodology, yearsOfExperience: number, company: { __typename?: 'Company', description?: string | null, domain: string }, workRole: { __typename?: 'WorkRole', description: string, id: string, name: string, seniority: string } };

export const SalaryFragmentDoc = gql`
    fragment Salary on Salary {
  amount
  company {
    description
    domain
  }
  countryCode
  currencyCode
  amount
  gender
  genderOtherText
  id
  typeOfEmployment
  workMetodology
  workRole {
    description
    id
    name
    seniority
  }
  yearsOfExperience
}
    `;