/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated. Please do not modify it manually. */
import * as Types from '../../../../api/gql/graphql';

import { gql } from '@apollo/client';
export type WorkEmailFragment = { __typename?: 'ValidatedWorkEmail', id: string, isValidated: boolean, status: Types.EmailStatus, workEmail: string, confirmationDate?: any | null };

export const WorkEmailFragmentDoc = gql`
    fragment WorkEmail on ValidatedWorkEmail {
  id
  isValidated
  status
  workEmail
  confirmationDate
}
    `;