import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import classNames from "classnames";
import { ThemeProvider } from "@/components/providers";
import { NavComponent } from "../components/Navbar/NavBarContext";
import { AuthLayout } from "../components/AuthLayout";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["500", "700", "900"],
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={classNames(
        " font-inter",
        // fonts
        [inter.variable, roboto.variable],
      )}
    >
      <body
        className={classNames(
          inter.variable,
          roboto.variable,
          "dark:bg-slate-950 bg-white",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthLayout>
            <NavComponent />
            {children}
          </AuthLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}

export const runtime = "edge"; // <--  Specifying edge runtime.
