import "./globals.css";
import classNames from "classnames";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers";
import { NavComponent } from "../components/Navbar/NavBarContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={classNames(" font-inter")}>
      <body className={classNames("dark:bg-slate-950 bg-white")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <NavComponent />
          </ClerkProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
