query GetWorkEmailsStatus {
  workEmails {
    id
    isValidated
    status
    workEmail
  }
  salaries {
    id
  }
  workRoles {
    description
    id
    name
    seniorities {
      id
      name
      description
    }
  }
}
